In [2]:
import pandas as pd
import numpy as np

# Initial global weather dataset cleaning, creation of new U.S. csv

In [5]:
# reading in the original file
# source: https://www.ncei.noaa.gov/data/global-summary-of-the-day/archive/

#df = pd.read_csv("combined-files.csv", skiprows=[3389713])
#df

In [7]:
# creating a new column with countries

#df["COUNTRY"] = df["NAME"].str[-2:]

# getting just U.S. data
#df = df[df["COUNTRY"] == "US"]

In [9]:
#df

In [11]:
# converting latitude and longitude to numeric values

# df["LAT_NUM"] = pd.to_numeric(df["LATITUDE"], errors="coerce")
# df["LON_NUM"] = pd.to_numeric(df["LONGITUDE"], errors="coerce")

In [13]:
# reseting index

#df = df.reset_index(drop=True)
#df

In [15]:
# creating a new weather CSV with just US data
# df.to_csv("large_weather_US.csv", index=False)

# Reading in new U.S. weather dataset

In [27]:
df = pd.read_csv("large_weather_US.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'large_weather_US.csv'

# Visualization of weather data for one day

In [25]:
import plotly.express as px
import pandas as pd

df_visualize = df[df["DATE"] == "2024-01-01"]

fig = px.scatter_mapbox(df_visualize, lat='LATITUDE', lon='LONGITUDE',
                          hover_name="NAME", zoom=3)
fig.update_layout(title='US Weather Data on Jan. 1, 2024', mapbox_style='open-street-map')
fig.update_layout(autosize=False, width=1000, height=600,margin=dict(l=0, r=0, t=50, b=0))

fig.show()

NameError: name 'df' is not defined

# Cleaning U.S. weather dataset & EDA

In [19]:
df.info()

NameError: name 'df' is not defined

In [23]:
# dropping irrelevant columns from df

df.drop(columns=["TEMP_ATTRIBUTES", "DEWP_ATTRIBUTES", "SLP_ATTRIBUTES", "STP_ATTRIBUTES", 
                 "VISIB_ATTRIBUTES", "WDSP_ATTRIBUTES", "MAX_ATTRIBUTES", "MIN_ATTRIBUTES",
                 "PRCP_ATTRIBUTES", "COUNTRY"], axis=1, inplace=True)

NameError: name 'df' is not defined

In [24]:
# replacing missing values with NaN (according to documentation)

df = df.replace(9999.9, np.nan)
df = df.replace(999.9, np.nan)
df = df.replace(99.9, np.nan)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768591 entries, 0 to 768590
Data columns (total 21 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   STATION    768591 non-null  int64
 1   DATE       768591 non-null  object
 2   LATITUDE   768591 non-null  float64
 3   LONGITUDE  768591 non-null  float64
 4   ELEVATION  768591 non-null  float64
 5   NAME       768591 non-null  object
 6   TEMP       768566 non-null  float64
 7   DEWP       765706 non-null  float64
 8   SLP        454849 non-null  float64
 9   STP        673907 non-null  float64
 10  VISIB      755162 non-null  float64
 11  WDSP       763591 non-null  float64
 12  MXSPD      761834 non-null  float64
 13  GUST       501242 non-null  float64
 14  MAX        767504 non-null  float64
 15  MIN        768214 non-null  float64
 16  PRCP       768591 non-null  float64
 17  SNDP       7856 non-null    float64
 18  FRSHTT     768591 non-null  int64
 19  LAT_NUM    768591 non-null  float64
 20  LON_NUM    768591 non-null  float64
dtypes: float64(17), int64(2), object(2)
memory usage: 123.1+ MB

In [31]:
# creating weather type columns

df["FRSHTT"] = df["FRSHTT"].astype(str).str.zfill(6)

df[["Fog", "Rain", "Snow", "Hail", "Thunder", "Tornado"]] = (
    df["FRSHTT"]
    .apply(list)          
    .apply(pd.Series) 
    .astype(int)
)

In [32]:
df

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,TEMP,DEWP,SLP,STP,...,SNDP,FRSHTT,LAT_NUM,LON_NUM,Fog,Rain,Snow,Hail,Thunder,Tornado
0,69015093121,2024-01-01,34.29400,-116.14722,610.5,"TWENTYNINE PALMS MC, CA US",46.5,36.3,1020.4,940.5,...,NaN,000000,34.29400,-116.14722,0,0,0,0,0,0
1,69015093121,2024-01-02,34.29400,-116.14722,610.5,"TWENTYNINE PALMS MC, CA US",49.3,33.7,1022.6,942.5,...,NaN,000000,34.29400,-116.14722,0,0,0,0,0,0
2,69015093121,2024-01-03,34.29400,-116.14722,610.5,"TWENTYNINE PALMS MC, CA US",47.2,35.1,1018.5,938.8,...,NaN,010000,34.29400,-116.14722,0,1,0,0,0,0
3,69015093121,2024-01-04,34.29400,-116.14722,610.5,"TWENTYNINE PALMS MC, CA US",48.8,30.1,1018.0,938.2,...,NaN,000000,34.29400,-116.14722,0,0,0,0,0,0
4,69015093121,2024-01-05,34.29400,-116.14722,610.5,"TWENTYNINE PALMS MC, CA US",47.7,28.6,1021.6,941.6,...,NaN,000000,34.29400,-116.14722,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768586,78551011624,2024-12-27,17.69965,-64.81249,14.0,"HENRY E. ROHLSEN AIRPORT, VI US",79.3,73.4,1014.2,12.3,...,NaN,010000,17.69965,-64.81249,0,1,0,0,0,0
768587,78551011624,2024-12-28,17.69965,-64.81249,14.0,"HENRY E. ROHLSEN AIRPORT, VI US",77.3,72.2,1014.8,13.1,...,NaN,010000,17.69965,-64.81249,0,1,0,0,0,0
768588,78551011624,2024-12-29,17.69965,-64.81249,14.0,"HENRY E. ROHLSEN AIRPORT, VI US",77.1,65.6,1014.9,13.1,...,NaN,000000,17.69965,-64.81249,0,0,0,0,0,0
768589,78551011624,2024-12-30,17.69965,-64.81249,14.0,"HENRY E. ROHLSEN AIRPORT, VI US",76.3,65.2,1014.1,12.3,...,NaN,010000,17.69965,-64.81249,0,1,0,0,0,0
768590,78551011624,2024-12-31,17.69965,-64.81249,14.0,"HENRY E. ROHLSEN AIRPORT, VI US",75.8,66.8,1014.1,12.5,...,NaN,010000,17.69965,-64.81249,0,1,0,0,0,0

# Combine with Cities Dataset

In [34]:
# locations of cities by latitude and longitude

# https://simplemaps.com/data/us-cities

cities = pd.read_csv('uscities.csv')

cols = ["city", "state_id", "state_name", "lat", "lng"]
cities = cities[cols]
cities

              city state_id    state_name      lat       lng
0         New York       NY      New York  40.6943  -73.9249
1      Los Angeles       CA    California  34.1141 -118.4068
2          Chicago       IL      Illinois  41.8375  -87.6866
3            Miami       FL       Florida  25.7840  -80.2101
4          Houston       TX         Texas  29.7860  -95.3885
...            ...      ...           ...      ...       ...
31252   Santa Cruz       AZ       Arizona  33.2327 -112.1594
31253   Frankstown       PA  Pennsylvania  40.4444  -78.3558
31254      Ski Gap       PA  Pennsylvania  40.3160  -78.5174
31255      Sherman       CT   Connecticut  41.5746  -73.4957
31256   Twin Lakes       CA    California  38.1695 -119.3422

[31257 rows x 5 columns]

In [35]:
import geopandas as gpd
from shapely.geometry import Point

# using geopandas to turn longitudes and latitudes into a single point

gdf_weather = gpd.GeoDataFrame(
    df, geometry=gpd.points_from_xy(df.LONGITUDE, df.LATITUDE), crs="EPSG:4326"
)

gdf_cities = gpd.GeoDataFrame(
    cities, geometry=gpd.points_from_xy(cities.lng, cities.lat), crs="EPSG:4326"
)

ModuleNotFoundError: No module named 'geopandas'

In [ ]:
# using geopandas to combine cities dataset with longitudes and latitudes from df/weather dataset
# need to specify variation in longitudes and latitudes to combine
weather_geo = gdf_weather.to_crs(epsg=32631)
cities_geo = gdf_cities.to_crs(epsg=32631)

joined_weather_cities = gpd.sjoin_nearest(weather_geo, cities_geo, how="inner", max_distance=35000)
# choosing 35000m ~ 21 miles distance from point

joined_weather_cities = joined_weather_cities[joined_weather_cities["state_name"] != "Puerto Rico"]
# removing Puerto Rico to focus only on 50 states

joined_weather_cities

In [ ]:
joined_weather_cities = joined_weather_cities.reset_index(drop=True)
joined_weather_cities

In [ ]:
# creating a cleaned version of the combined weather and cities datasets

#joined_weather_cities.to_csv("weather_cities_cleaned.csv", index=False)

In [ ]:
df2 = pd.read_csv("weather_cities_cleaned.csv")
df2

In [ ]:
df2.info()